<a href="https://colab.research.google.com/github/KTIHAM/Data-Science-Prcatice-Sessions/blob/master/Data_Science.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
function = lambda a, b, c : a + b

In [ ]:
function (1, 2, 3)

3

In [ ]:
my_number = []

for number in range(0, 10):
    if number%2 == 0:
        my_number.append(number)
      
print (my_number)

[0, 2, 4, 6, 8]


In [ ]:
my_list = [number for number in range(0, 15) if number % 2 != 0 ]
print (my_list)

[1, 3, 5, 7, 9, 11, 13]


In [ ]:
lowercase = 'abcdefghijklmnopqrstuvwxyz'
digits = '0123456789'

user_id = [x+y+z+w for x in lowercase for y in lowercase for z in digits for w in digits]

print(user_id[:50])

['aa00', 'aa01', 'aa02', 'aa03', 'aa04', 'aa05', 'aa06', 'aa07', 'aa08', 'aa09', 'aa10', 'aa11', 'aa12', 'aa13', 'aa14', 'aa15', 'aa16', 'aa17', 'aa18', 'aa19', 'aa20', 'aa21', 'aa22', 'aa23', 'aa24', 'aa25', 'aa26', 'aa27', 'aa28', 'aa29', 'aa30', 'aa31', 'aa32', 'aa33', 'aa34', 'aa35', 'aa36', 'aa37', 'aa38', 'aa39', 'aa40', 'aa41', 'aa42', 'aa43', 'aa44', 'aa45', 'aa46', 'aa47', 'aa48', 'aa49']


In [ ]:
import numpy as np

In [ ]:
mylist = [1, 2, 3]
x = np.array(mylist)
x

array([1, 2, 3])

In [ ]:
y = np.array([4, 5, 6])
y

array([4, 5, 6])

In [ ]:
m = np.array([[9, 6, 5], [8, 7, 8]])
print(m)
m.shape

[[9 6 5]
 [8 7 8]]


(2, 3)

In [ ]:
n= np.arange(1 ,30, 2)
n

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29])

In [ ]:
n = n.reshape(3, 5)
n

array([[ 1,  3,  5,  7,  9],
       [11, 13, 15, 17, 19],
       [21, 23, 25, 27, 29]])

In [ ]:
o = np.linspace(0, 4, 9)
o

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. ])

In [ ]:
o.resize(3,3)
o

array([[0. , 0.5, 1. ],
       [1.5, 2. , 2.5],
       [3. , 3.5, 4. ]])

In [ ]:
np.ones((3, 2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [ ]:
np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
np.diag(y)

array([[4, 0, 0],
       [0, 5, 0],
       [0, 0, 6]])

In [ ]:
np.array([1, 2, 3] * 2)

array([1, 2, 3, 1, 2, 3])

In [ ]:
np.repeat([1, 2, 3], 3)

array([1, 1, 1, 2, 2, 2, 3, 3, 3])

In [ ]:
p = np.ones([2, 3], int)
p

array([[1, 1, 1],
       [1, 1, 1]])

In [ ]:
np.hstack([p, 2*p])

array([[1, 1, 1, 2, 2, 2],
       [1, 1, 1, 2, 2, 2]])

In [ ]:


x.dot(y)

32

In [ ]:
z = np.array([y, y**2])
z

array([[ 4,  5,  6],
       [16, 25, 36]])

In [ ]:
z.T

array([[ 4, 16],
       [ 5, 25],
       [ 6, 36]])

In [ ]:
z.shape

(2, 3)

In [ ]:
z.dtype

dtype('int64')

In [ ]:
z = z.astype('f')
z.dtype

dtype('float32')

In [ ]:
a = np.array([-4, -3, -1, 3, 5, 6])
a

array([-4, -3, -1,  3,  5,  6])

In [ ]:
a.sum()

6

In [ ]:
a.argmax()

5

In [ ]:
s = np.arange(13)**2
s

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144])

In [ ]:
s[0], s[4], s[0:3]


(0, 16, array([0, 1, 4]))

In [ ]:
s[1:5]

array([ 1,  4,  9, 16])

In [ ]:
s[-4:]

array([ 81, 100, 121, 144])

In [ ]:
s[-5::2]

array([ 64, 100, 144])

In [ ]:
r = np.arange(36)
r.resize((6, 6))
r

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [ ]:
r[2:4, 2:4]

array([[14, 15],
       [20, 21]])

In [ ]:
r[2:4, 2:4]

array([[14, 15],
       [20, 21]])

In [ ]:
r[3, 3:6]

array([21, 22, 23])

In [ ]:
r[:2, :-1]

array([[ 0,  1,  2,  3,  4],
       [ 6,  7,  8,  9, 10]])

In [ ]:
r[-1, ::2]

array([30, 32, 34])

In [ ]:
r[r > 30] = 30
r

array([[ 0,  0,  0,  3,  4,  5],
       [ 0,  0,  0,  9, 10, 11],
       [ 0,  0,  0, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 30, 30, 30, 30, 30]])

In [ ]:
r2 = r[:3, :3]
r2

array([[ 0,  1,  2],
       [ 6,  7,  8],
       [12, 13, 14]])

In [ ]:
r2[:] = 0
r2

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [ ]:
r

array([[ 0,  0,  0,  3,  4,  5],
       [ 0,  0,  0,  9, 10, 11],
       [ 0,  0,  0, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 30, 30, 30, 30, 30]])

In [ ]:
r_copy = r.copy()
r_copy

array([[ 0,  0,  0,  3,  4,  5],
       [ 0,  0,  0,  9, 10, 11],
       [ 0,  0,  0, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 30, 30, 30, 30, 30]])

In [ ]:
r_copy[:] = 10
print(r_copy)
print()
print(r)

[[10 10 10 10 10 10]
 [10 10 10 10 10 10]
 [10 10 10 10 10 10]
 [10 10 10 10 10 10]
 [10 10 10 10 10 10]
 [10 10 10 10 10 10]]

[[ 0  0  0  3  4  5]
 [ 0  0  0  9 10 11]
 [ 0  0  0 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 30 30 30 30 30]]


In [ ]:
old = np.array([[1, 1, 1],
                [1, 1, 1]])

new = old
new[0, :2] = 0

print(old)


[[0 0 1]
 [1 1 1]]


In [ ]:
test = np.random.randint(0, 10, (4, 3))
test

array([[8, 4, 6],
       [6, 1, 8],
       [0, 6, 6],
       [8, 5, 4]])

In [ ]:
for row in test:
  print(row)

[8 4 6]
[6 1 8]
[0 6 6]
[8 5 4]


In [ ]:
for i in range(len(test)):
  print(test[i])

[8 4 6]
[6 1 8]
[0 6 6]
[8 5 4]


In [ ]:
for i, row in enumerate(test):
      print('row', i, 'is', row)

row 0 is [8 4 6]
row 1 is [6 1 8]
row 2 is [0 6 6]
row 3 is [8 5 4]


In [ ]:
test2 = test**2
test2

array([[64, 16, 36],
       [36,  1, 64],
       [ 0, 36, 36],
       [64, 25, 16]])

In [ ]:
for i, j in zip(test, test2):
      print(i, '+', j, '=', i + j)

[8 4 6] + [64 16 36] = [72 20 42]
[6 1 8] + [36  1 64] = [42  2 72]
[0 6 6] + [ 0 36 36] = [ 0 42 42]
[8 5 4] + [64 25 16] = [72 30 20]


In [ ]:
def solution(i):
    # printing output
    primes = get_primes()
    return primes[i:i+5]
    
def get_primes():
    
    string = ''
    new_prime = 2
    while len(string) < 10005:
        
        #Pushing Primes in String
        string += str(new_prime)
        
        #next prime
        new_prime += 1
        while not verify_prime(new_prime):
            new_prime += 1
        
    return string

def verify_prime(number):
    #Verifying prime number
    
    for i in range(2, number):
        if number % i == 0:
            return False
    return True
        
print(solution(0))

print(solution(3))


23571
71113


In [ ]:
def solution(l, t):
    #declaring starting and ending endex
    i = 0
    j = 0
    
    while i <= j and j < len(l):
        addition = sum ( l [i : j + 1] )
        if addition == t:
            return [i, j]
        elif addition < t:
            j += 1
        else:
            i += 1
            j = max(i, j)

    return [-1, -1]